# Generated by Django 3.1.4 on 2020-12-23 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='s_age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='market',
            name='s_grade',
            field=models.IntegerField(default=0),
        ),
    ]
