# Generated by Django 3.1.4 on 2020-12-23 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_auto_20201223_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=100)),
                ('YM', models.IntegerField(default=0)),
                ('BAS_ID', models.CharField(max_length=10)),
                ('totalspent', models.IntegerField(default=0)),
                ('Disspent', models.IntegerField(default=0)),
                ('Numofspent', models.IntegerField(default=0)),
                ('NumofDisspent', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='market',
        ),
    ]
